---
title: "Finding a Shared Motif"
author: "Dominic Pearce"
date: "9 March 2016"
output:
  github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
#library(seqinr)
#asdf <- read.fasta("~/Downloads/rosalind_lcsm.txt")

#qwer <- unlist(lapply(asdf, function(x) paste0(x, collapse = "")))

input.lst <- list(">Rosalind_1 GATTACA", ">Rosalind_2 TAGACCA", ">Rosalind_3 ATACA")

nt = sapply(input.lst, function(x) substr(x, (which(strsplit(x, "")[[1]] == " ") + 1), nchar(x)))

nt
```

## Chomper function
```{r}
pieces <- function(nt.seq){

  lil.bits <- as.vector(sapply(1:nchar(nt.seq), function(x) sapply(1:nchar(nt.seq), function(y) substr(nt.seq, x, y))))

  blanks <- which(lil.bits == "")
  singles <- which(nchar(lil.bits) == 1)

  lil.bits[-c(blanks, singles)]
}
```

## Do the chomping
```{r}
#rewq <- lapply(nt, pieces)

all.pieces.lst <- lapply(nt, pieces)

all.pieces.lst
```

## Arrange as one object and count common substrings with `table()`
```{r}
#poiu <- unlist(rewq)

all.pieces <- unlist(all.pieces.lst)

all.pieces

table(all.pieces)
```

## Then subset by only those substrings found in each of the original strings and choose the longest
```{r}
#uiop <- table(poiu)[table(poiu) == length(qwer)]

common.pieces <- table(all.pieces)[table(all.pieces) == length(nt)]

common.pieces

#names(uiop[which.max(nchar(names(uiop)))])

names(common.pieces[which.max(nchar(names(common.pieces)))])
```
