---
title: "Open Reading Frames"
author: "Dominic Pearce"
date: "15 March 2016"
output: html_document
---

## Firstly, a couple of functions from previous puzzles
 - Reverse complement
 - Translate RNA
 
```{r, include=FALSE}
revC <- function(x) {
  input <- strsplit(x, "")[[1]]
  
  complement <- gsub("2", "G", gsub("1", "T", gsub("G", "C", gsub("T", "A", gsub("C", "2", gsub("A", "1", input))))))
  
  paste(rev(complement), collapse = "")
}


translateRNA <- function(oligonucleotide) {
  
  translator <- data.frame(AA = c("F", "L", "I", "V", "F", "L", "I", "V", "L", "L", "I", "V", "L", "L", "M", "V", "S", "P", "T", "A", "S", "P", "T", "A", "S", "P", "T", "A", "S", "P", "T", "A", "Y", "H", "N", "D", "Y", "H", "N", "D", "Stop", "Q", "K", "E", "Stop", "Q", "K", "E", "C", "R", "S", "G", "C", "R", "S", "G", "Stop", "R", "R", "G", "W", "R", "R", "G"), codons = c("TTT", "CTT", "ATT", "GTT", "TTC", "CTC", "ATC", "GTC", "TTA", "CTA", "ATA", "GTA", "TTG", "CTG", "ATG", "GTG", "TCT", "CCT", "ACT", "GCT", "TCC", "CCC", "ACC", "GCC", "TCA", "CCA", "ACA", "GCA", "TCG", "CCG", "ACG", "GCG", "TAT", "CAT", "AAT", "GAT", "TAC", "CAC", "AAC", "GAC", "TAA", "CAA", "AAA", "GAA", "TAG", "CAG", "AAG", "GAG", "TGT", "CGT", "AGT", "GGT", "TGC", "CGC", "AGC", "GGC", "TGA", "CGA", "AGA", "GGA", "TGG", "CGG", "AGG", "GGG"), stringsAsFactors = FALSE)
row.names(translator) <- translator$codons
  
  rna.input <- substring(oligonucleotide, seq(1, nchar(oligonucleotide), 3), seq(3, nchar(oligonucleotide), 3))
  
  protein.output <- translator[rna.input[1:(length(rna.input)-1)], 1]
  
  paste0(protein.output, collapse = "")
}

```

## Then we use a function that is defined by the region of our input that starts with "ATG" and the first subsequent stop codon
```{r}
findORF <- function(RNA, orf.index) {
  
  stop <- c("TAG", "TGA", "TAA")
  
  orf <- substring(RNA, orf.index, nchar(RNA))
  
  all.stop <- unlist(lapply(stop, function(y) as.numeric(gregexpr(y, orf)[[1]])))
  
  orf.stop <- min(all.stop[which(all.stop%%3 == 1)])
                  
  substring(orf, 1, orf.stop)
}


ros.func <- function(RNA){

  suppressWarnings(
    unique(
      unlist(
        lapply(c(RNA, revC(RNA)), function(nucs) {
          
          orf.index <- as.numeric(gregexpr("ATG", nucs)[[1]])
          
          RNA.orfs <- sapply(orf.index, function(x) findORF(nucs, x))
          
          unlist(lapply(na.omit(RNA.orfs), function(x) translateRNA(x)))
        }
        )
      )
    )
  )
}


input <- paste0(readLines("C:/Users/s1460988/Downloads/rosalind_orf.txt")[-1], collapse = "")

cat(ros.func(input), sep = "\n")
```

