---
title: "Calculating Protein Mass"
author: "Dominic Pearce"
date: "15 March 2016"
output: html_document
---


## Create dataframe with amino acids and corersponding weights
Set `row.names()` to aa symbols to allow subsetting of the dataframe
```{r}
weight.dict <- data.frame(weight = c(71.03711, 103.00919, 115.02694, 129.04259, 147.06841, 57.02146, 137.05891, 113.08406, 128.09496, 113.08406, 131.04049, 114.04293, 97.05276, 128.05858, 156.10111, 87.03203, 101.04768, 99.06841, 186.07931, 163.06333), stringsAsFactors = FALSE)

row.names(weight.dict) <- c("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y") 

knitr::kable(weight.dict)
```

## Subset dataframe by the amino acids present in our polypeptide
note: set `options(digits = )` to a higher value otherwise Rosalind doesn't like the answer
```{r}
input.seq <- strsplit(readLines("C:/Users/domin/Downloads/rosalind_prtm (3).txt"), split = "")[[1]]

options(digits = 10)

cat(sum(weight.dict[input.seq,]))
```

