---
title: "Longest In-/Decreasing Substring"
author: "Dominic Pearce"
date: "28 April 2016"
output: html_document
---

```{r}
input <- c(7, 9, 8, 10, 12, 5, 3, 6, 11, 2, 1, 4, 13)
len <- length(input)

asdf <- lapply(input[2:len], function(x) c(input[1], x))
#asdf <- asdf[which(unlist(lapply(asdf, function(x) identical(x, sort(x)))))]
```

```{r}
ssFinder <- function(input, len, asdf) {
  
  
  fdsa <- unlist(lapply(asdf, function(x) 
  lapply(na.omit(input[which(input == x[length(x)])+1:len]), function(y) 
    c(x, y)
    )), recursive = FALSE)
  
  if (length(fdsa) == 0) {
    asdf
  } else {
      
  fdsa <- fdsa[which(unlist(lapply(fdsa, function(x) identical(x, sort(x)))))]
  
  if (
    length(fdsa) == 0
    ){
    asdf
    } else {
      asdf <- fdsa
      
      
      ssFinder(input, len, asdf)
    }
  }
}
```

```{r}
input.base <- as.numeric(strsplit(readLines("~/Downloads/rosalind_lgis-2.txt")[2], " ")[[1]])
```

```{r}
input <- input.base[1:60]
len <- length(input)

input.list <- lapply(1:len, function(x) input[x:len])

output <- list()

system.time(for (i in 1:(len-1)){
#i = 1
asdf <- lapply(na.omit(input.list[[i]][2:len]), function(x) c(input.list[[i]][1], x))
asdf <- asdf[which(unlist(lapply(asdf, function(x) identical(x, sort(x)))))]

  
output[[i]] <- ssFinder(input.list[[i]], len, asdf)
}
)

unlist(output, recursive = FALSE)[[which.max(lapply(unlist(output, recursive = FALSE), length))]]

```














































